### ISSUE TITLE
No `solib_address` on gdb 8.1 results in runtime error

### ISSUE THREAD

**Issue by eullerborges** [jmk/gdb-utils#1]
When running this under gdb 8.1 I get:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gdb-utils/auto_load_solibs.py", line 99, in auto_load_all
    auto_load_symbols(verbose)
  File "/gdb-utils/auto_load_solibs.py", line 85, in auto_load_symbols
    newLoaded = load_symbols(frames, verbose)
  File "/gdb-utils/auto_load_solibs.py", line 47, in load_symbols
    lib = gdb.solib_address(sal.pc)
AttributeError: 'module' object has no attribute 'solib_address'
Error while executing Python code.
```
Any thoughts on how to solve that? It looks like `solib_address` is not being exposed anymore.

This is really what I was looking for, thanks for developing this.

**Comment by eullerborges** [comment]
I found out the problem, `solib_address` is now `solib_name` (which makes more sense, really, as it retrieves the name of the library).
It works like a charm now! I'll track where the change happened on gdb and contribute with a patch.

**Comment by jmk** [comment]
Hi Euller,

Thanks! I'm still using an older version of gdb (7.x) so I had no idea. Thank you for the note, and if you have a patch I'd be happy to take a look. Hope you find this useful!
